name: homelab
on:
  push:
    branches:
      - main # or the name of your main branch
jobs:
  # SonarQube Scan
  build:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # Scan manifests
  # scan-static-manifests:
  #   name: Scan Manifests with Trivy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Run Trivy vulnerability scanner in IaC mode
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: "config"
  #         hide-progress: false
  #         ignore-unfixed: true
  #         format: 'json'
  #         severity: "CRITICAL,HIGH,MEDIUM"
  #         # format: "template"
  #         # template: "@/contrib/sarif.tpl"
  #         output: "trivy-results.sarif"
  #         # Normally on a PR, we'd want exit code 1.
  #         # For straight commits, we want it to be 0.
  #         # exit-code: '1'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v1
  #       with:
  #         sarif_file: "trivy-results.sarif"
